services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./auth:/app

  notes:
    build:
      context: .
      dockerfile: notes/Dockerfile
    container_name: notes
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ./notes:/app

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - notes
    volumes:
      - ./gateway:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
