services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth
    ports:
      - "8001:8000"
    env_file:
      - ./auth/.env
    depends_on:
      - db
    volumes:
      - ./auth:/app

  notes:
    build:
      context: ./notes
    container_name: notes
    ports:
      - "8002:8000"
    env_file:
      - ./notes/.env
    volumes:
      - ./notes:/app

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - notes
    volumes:
      - ./gateway:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
